In [1]:
from sklearn.datasets import load_iris

x, y = load_iris(return_X_y=True)

In [16]:
x.shape

(150, 4)

In [3]:
y.shape

(150,)

In [12]:
from CKMeans import CKMeans

ckmeans = CKMeans(n_clusters=4, random_state=42)
ckmeans.fit(x, y)

In [13]:
labels = ckmeans.labels_
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 3, 3, 3, 2, 3, 3, 3, 2, 3, 2, 2, 3, 2, 3, 2, 3,
       3, 2, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 3, 2, 3, 3, 3,
       2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
index = labels==19
y[index]

array([], dtype=int32)

In [15]:
for i in range(20):
    index = labels==i
    print(y[index])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]


In [30]:
d[0][0]

3.4641016151377544

In [28]:
x = d**2
x[0][0]

11.999999999999998

In [11]:
y = np.array([[3, 2, 1, 2]])
y.shape

(1, 4)

In [25]:
a = [1, 2, 3, 4]
b = (a**2).sum()
b

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
x.reshape(-1, 1)

array([[3],
       [2],
       [1],
       [2]])