In [15]:
import pandas as pd
import numpy as np
from random import sample
from sklearn.preprocessing import LabelEncoder

letter = pd.read_csv("./dataset/letter_csv.csv")
data = letter.to_numpy()
labels = data[:, -1]
data = data[:, :-1]
le = LabelEncoder()
labels = le.fit_transform(labels)
classes = np.unique(labels)

In [34]:
train_set = sample(classes.tolist(), 10)
set_ = list(set(classes) - set(train_set))
set_

[2, 4, 5, 6, 8, 9, 10, 11, 14, 15, 17, 19, 20, 21, 23, 25]

In [32]:
index = [i in train_set for i in labels]
len(index)

20000

In [13]:
a = list(range(10))
b = list(range(5))
print(i in b for i in a)

<generator object <genexpr> at 0x7f035c47d150>


In [14]:
index = labels==19
y[index]

array([], dtype=int32)

In [15]:
for i in range(20):
    index = labels==i
    print(y[index])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]


In [30]:
d[0][0]

3.4641016151377544

In [28]:
x = d**2
x[0][0]

11.999999999999998

In [11]:
y = np.array([[3, 2, 1, 2]])
y.shape

(1, 4)

In [25]:
a = [1, 2, 3, 4]
b = (a**2).sum()
b

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
x.reshape(-1, 1)

array([[3],
       [2],
       [1],
       [2]])